# Handling board and detecting winners

## Idea 1: Bitwise Operations

- `Game` or `Board` object stores current state as N x N matrix, which allows easy setting/getting (board[x,y])
- After each move, a method converts this to a binary string, where 1's represent positions held by current player.
    [[X, O,  ],
     [O, X, O],
     [ , X,  ]]
     
     --> 100010010
- This string is compared to each of the 8 winning string operations using bitwise operation: cur_position & 111000000 == 111000000
- If there's a match we have a winner

In [1]:
winners = [
    0b111000000,
    0b000111000,
    0b000000111,
    0b100100100,
    0b010010010,
    0b001001001,
    0b100010001,
    0b001010100
]

In [2]:
cur_position = 0b010000011

def check(cur_position):
    for winner in winners:
        if winner & cur_position == winner:
            print('Winner')
            return
    print('no winner')
    return

check(cur_position)

no winner


In [17]:
board = [['X', 'O', '_',],
         ['X', '_', 'O'],
         ['O', 'X', 'X']]

board

[['X', 'O', '_'], ['X', '_', 'O'], ['O', 'X', 'X']]

In [18]:
def flatten(board):
    return [item for row in board for item in row]

def encode(flat_board, playerchar):
    binseq = '0b'
    for char in flat_board:
        if char == playerchar:
            binseq += '1'
        else:
            binseq += '0'
    return int(binseq, 2)

In [19]:
board = [['X', 'O', '_',],
         ['X', 'X', 'O'],
         ['O', 'O', 'X']]

check(encode(flatten(board), 'X'))

Winner


In [27]:
def newboard(): return [['', '', ''],['', '', ''], ['','','']]

board = newboard()

board[0][1] = 'X'
board[0][0] = 'X'
board[0][2] = 'X'

check(encode(flatten(board), 'X'))

Winner


# Idea 2: Summing Rows, Columns, and Diagonals (from scratch)
- Board initialized with zeroes.
- Board stores `1` for player 1 moves and `-1` for player 2 moves. A row, column, or diagonal that sums to 3 is a win for player 1, -3 a win for player 2.
- To simpllify checking, check only rows and diagonal and then transpose matrix and recheck

In [20]:
board = [[1, -1, 0], [0, 0, 1], [-1, -1, 1]]
board

[[1, -1, 0], [0, 0, 1], [-1, -1, 1]]

In [21]:
def sumrows(board):
    rowresults = []
    for row in board:
        result = 0
        for col in row:
            result += col
        rowresults.append(result)
    return rowresults

def sumdiag(board):
    n = len(board)
    result = 0
    for i in range(n):
        result += board[i][i]
    return result

print('Rows: {}'.format(sumrows(board)))
print('Diagonal: {}'.format(sumdiag(board)))

Rows: [0, 1, -1]
Diagonal: 2


In [22]:
def transpose(board):
    newboard = [['','',''],['','',''],['','','']]
    for row in range(len(board)):
        for col in range(len(board[row])):
            newboard[row][col] = board[col][row]
    return newboard

def reverse_row_inplace(row):
    l = 0
    r = len(a) - 1
    while l < r:
        row[l], row[r] = row[r], row[l]
        l += 1
        r -= 1
    return row

def reverse_row(row):
    newrow = []
    i = len(row) - 1
    while i >= 0:
        newrow.append(row[i])
        i -= 1
    return newrow

def mirror(board):
    newboard = []
    for row in board:
        newboard.append(reverse_row(row))
    return newboard

def rotate90(board):
    return transpose(mirror(board))

In [23]:
print('Columns: {}'.format(sumrows(rotate90(board))))
print('Reverse Diagonal: {}'.format(sumdiag(rotate90(board))))

Columns: [2, -2, 0]
Reverse Diagonal: -1


# Idea 3: Same as Above, but with NumPy

In [136]:
import numpy as np

In [137]:
board = np.array([[1, -1, 0], [0, 0, 1], [-1, -1, 1]])
board

array([[ 1, -1,  0],
       [ 0,  0,  1],
       [-1, -1,  1]])

In [138]:
# Sum diagonal
a.diagonal().sum()

2

In [139]:
# Sum rows
a.sum(axis=1)

array([ 0,  1, -1])

In [140]:
# Sum cols
a.sum(axis=0)

array([ 0, -2,  2])

In [142]:
# Sum anti-diagonal
np.fliplr(a).diagonal().sum()

-1

# TO DO:
- Think about class diagram and classes and what each needs to do
- Think about generalizing solution to N x N grid
- Remind self how to prompt for input
- Board object should be a multidimensional array so that user can prompt e.g. `1, 2` for row 1, column 2
- Think through general workflow:
 - Initialize board object
 - Prompt player 1 for move
 - Add Player 1 move to board object
 - Keep track of turn count. Use count % 2 (number of players) to determine what player it is
 - If turn coIf it's move 3 or higher, check for winner
 - If winner, game over; otherwise next player

In [144]:
0 % 2

0

In [146]:
2 // 2

1